
//
// This file was machine generated by MkID.bat.
// Do not modify.
// 
// Contact: msotbqs, "Office Commandbar questions"
//

#ifndef TMPBAR_H
#define TMPBAR_H

enum
	{
	msotbidTemporaryMin = msotbidRealMax,
#ifdef VSMSODEBUG
	msotbidWebServerDebugMenu,
	msotbidPaneSample,
#endif  // VSMSODEBUG
	msotbidMax
	};

#endif // TMPBAR_H

