//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualBasic;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System;
namespace Econ.Netvert.Gui.My.Resources
{

  //This Class was auto-generated by the StronglyTypedResourceBuilder
  //Class via a tool like ResGen or Visual Studio.
  //To add or remove a member, edit your .ResX file then rerun ResGen
  //with the /str option, or rebuild your VS project.
  ///<summary>
  ///  A strongly-typed resource class, for looking up localized strings, etc.
  ///</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
  internal class Resources
  {

    private global::System.Resources.ResourceManager resourceMan;

    private global::System.Globalization.CultureInfo resourceCulture;

    ///<summary>
    ///  Returns the cached ResourceManager instance used by this class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Econ.Netvert.Gui.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    ///<summary>
    ///  Overrides the current thread's CurrentUICulture property for all
    ///  resource lookups using this strongly typed resource class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal global::System.Globalization.CultureInfo Culture {
      get { return resourceCulture; }
      set { resourceCulture = value; }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap CS_to_VB_16 {
      get {
        object obj = ResourceManager.GetObject("CS_to_VB_16", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap CS_to_VB2_16 {
      get {
        object obj = ResourceManager.GetObject("CS_to_VB2_16", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap Go {
      get {
        object obj = ResourceManager.GetObject("Go", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap VB_to_CS_16 {
      get {
        object obj = ResourceManager.GetObject("VB_to_CS_16", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap VB_to_CS2_16 {
      get {
        object obj = ResourceManager.GetObject("VB_to_CS2_16", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap window {
      get {
        object obj = ResourceManager.GetObject("window", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }

    ///<summary>
    ///  Looks up a localized resource of type System.Drawing.Bitmap.
    ///</summary>
    internal System.Drawing.Bitmap XP_Exit_16 {
      get {
        object obj = ResourceManager.GetObject("XP_Exit_16", resourceCulture);
        return (System.Drawing.Bitmap)obj;
      }
    }
  }
}

